### PR TITLE
Update to Python3 compatibility, platform detection

### PR DESCRIPTION
**Pull request by jayceelock**
This pull adds a script to detect the platform more accurately, taken from the base py-gauegette repo, since Pi v3 wasn't properly detected. Also Made some fixes to make it compatible with Python3 (print statements, division errors, etc.)

### CODE REVIEW

**Comment by boxysean** [comment]
Hi thanks for your PR. Is there something in particular you are using from my fork that isn't in the main fork? I don't maintain this, maybe it would make sense for you to do a PR to @guyc's repo?

**Comment by jayceelock** [comment]
Hi, yes, I've been using your SSD1351 driver and sample for a project and I thought it would be a good addition to the base branch of @guyc.

I thought it might've been in bad taste to submit a PR directly using your code, but if you're ok with it, I can submit a PR to the base branch to add the SSD1351 code and note you as the original author

**Comment by boxysean** [comment]
I'm happy that this helped you! Yes I'm fully okay with you to merge what you'd like into the main fork. I'm not at all concerned with credit for this work, but thank you for being courteous.

**Comment by jayceelock** [comment]
Ok great, I've submitted the PR to the main fork :) I'll go ahead and close this PR then

**Pull request closed without merging**
